import type { Config } from "tailwindcss"

export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  safelist: [
    // helpful when building dynamic classes
    { pattern: /(bg|from|to|via|text|border|ring)-(brand|neutral)-(50|100|200|300|400|500|600|700|800|900)/ },
    { pattern: /(bg|text|border|ring)-(success|warning|danger)/ },
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1rem",
        md: "1.25rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "2.5rem",
      },
      screens: {
        xs: "360px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
      },
    },
    extend: {
      screens: {
        tall: { raw: "(min-height: 740px)" },
        short: { raw: "(max-height: 680px)" },
      },
      colors: {
        neutral: {
          900: "#0F172A",
          800: "#1E293B",
          700: "#334155",
          600: "#475569",
          500: "#64748B",
          400: "#94A3B8",
          300: "#CBD5E1",
          200: "#E2E8F0",
          100: "#F1F5F9",
          50:  "#F8FAFC",
          0:   "#FFFFFF",
        },
        brand: {
          700: "#9E6D05",
          600: "#B87D05",
          500: "#DF9D07",
          400: "#F1B52F",
          300: "#F1CC77",
          200: "#F5DDA8",
          100: "#FBF0D6",
          50:  "#FEF9ED",
          // high-contrast foreground on brand backgrounds
          foreground: "#0E0A02",
        },
        success: "#16A34A",
        warning: "#F59E0B",
        danger:  "#DC2626",

        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        sans: ["Inter", "SF Pro Display", "system-ui", "sans-serif"],
        display: ["Inter", "SF Pro Display", "system-ui", "sans-serif"],
        mono: ["SF Mono", "Monaco", "Consolas", "monospace"],
      },
      fontSize: {
        xs:   ["0.75rem",  { lineHeight: "1rem",   letterSpacing: "0.025em" }],
        sm:   ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.025em" }],
        base: ["1rem",     { lineHeight: "1.5rem" }],
        lg:   ["1.125rem", { lineHeight: "1.75rem" }],
        xl:   ["1.25rem",  { lineHeight: "1.75rem", letterSpacing: "-0.015em" }],
        "2xl":["1.375rem", { lineHeight: "2rem",   letterSpacing: "-0.02em" }],
        "3xl":["1.5rem",   { lineHeight: "2rem",   letterSpacing: "-0.02em" }],
        "4xl":["1.875rem", { lineHeight: "2.25rem",letterSpacing: "-0.02em" }],
        "5xl":["2.25rem",  { lineHeight: "2.5rem", letterSpacing: "-0.025em" }],
      },
      spacing: {
        "0.5": "2px",
        "1":   "4px",
        "1.5": "6px",
        "2":   "8px",
        "3":   "12px",
        "4":   "16px",
        "5":   "20px",
        "6":   "24px",
        "8":   "32px",
        "10":  "40px",
        "12":  "48px",
        "16":  "64px",
        "20":  "80px",
        "24":  "96px",
        "32":  "128px",
        "40":  "160px",
        "48":  "192px",
        "56":  "224px",
        "64":  "256px",
        comfortable: "var(--spacing-comfortable, 1rem)",
        compact: "var(--spacing-compact, 0.5rem)",
        "safe-top": "var(--safe-area-inset-top)",
        "safe-bottom": "var(--safe-area-inset-bottom)",
        "safe-left": "var(--safe-area-inset-left)",
        "safe-right": "var(--safe-area-inset-right)",
        "safe-or-2": "max(env(safe-area-inset-bottom, 0rem), 0.5rem)",
        "safe-or-4": "max(env(safe-area-inset-bottom, 0rem), 1rem)",
        "safe-top-or-2": "max(env(safe-area-inset-top, 0rem), 0.5rem)",
        "safe-top-or-4": "max(env(safe-area-inset-top, 0rem), 1rem)",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        pill: "9999px",
        "xs-var": "var(--radius-xs)",
        "sm-var": "var(--radius-sm)",
        "md-var": "var(--radius-md)",
        "lg-var": "var(--radius-lg)",
        "xl-var": "var(--radius-xl)",
        "2xl-var": "var(--radius-2xl)",
        "3xl-var": "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        subtle:   "0 1px 2px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.06)",
        card:     "0 1px 2px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.06)",
        elevated: "0 4px 12px rgba(0,0,0,0.08), 0 16px 32px rgba(0,0,0,0.12)",
        focus:    "0 0 0 3px rgba(223,157,7,0.18)",
        brand:    "0 0 0 3px rgba(223,157,7,0.18)",
        // keep variables
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        glow: "var(--shadow-glow)",
        elevated2: "0 10px 30px rgba(0,0,0,0.18)",
      },
      backdropBlur: {
        glass: "20px",
      },
      backdropSaturate: {
        125: "1.25",
        150: "1.5",
      },
      backdropBrightness: {
        90: "0.90",
        110: "1.10",
      },
      ringWidth: {
        3: "3px",
      },
      ringOffsetWidth: {
        2: "2px",
        3: "3px",
      },
      gradientColorStops: ({ theme }) => ({
        ...theme("colors"),
      }),
      transitionTimingFunction: {
        ios: "cubic-bezier(.22,.61,.36,1)",
        "ios-in-out": "cubic-bezier(.32,.72,.0,1)",
        spring: "cubic-bezier(.2,.8,.2,1)",
      },
      transitionDuration: {
        fast: "120ms",
        normal: "200ms",
        slow: "300ms",
        quick: "200ms",
        smooth: "300ms",
        spring: "400ms",
      },
      zIndex: {
        rail: "40",
        toast: "50",
        modal: "50",
        popover: "100",
        dropdown: "100",
      },
      minHeight: {
        dvh: "100dvh",
      },
      opacity: {
        15: "0.15",
        85: "0.85",
        95: "0.95",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in":   { "0%": { opacity: "0", transform: "translateY(10px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-out":  { "0%": { opacity: "1", transform: "translateY(0)" }, "100%": { opacity: "0", transform: "translateY(10px)" } },
        "slide-up":  { "0%": { transform: "translateY(100%)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        "slide-down":{ "0%": { transform: "translateY(-100%)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        "scale-in":  { "0%": { transform: "scale(0.95)", opacity: "0" }, "100%": { transform: "scale(1)", opacity: "1" } },
        shimmer:     { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "fade-in":   "fade-in 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
        "fade-out":  "fade-out 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        "slide-up":  "slide-up 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
        "slide-down":"slide-down 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
        "scale-in":  "scale-in 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        shimmer:     "shimmer 2s linear infinite",
      },
      typography: ({ theme }: { theme: (path: string) => any }) => ({
        DEFAULT: {
          css: {
            color: theme("colors.neutral.800"),
            h1: { color: theme("colors.neutral.900"), letterSpacing: "-0.02em" },
            h2: { color: theme("colors.neutral.900"), letterSpacing: "-0.02em" },
            h3: { color: theme("colors.neutral.900") },
            a:  { color: theme("colors.brand.600"), textDecoration: "none" },
            strong: { color: theme("colors.neutral.900") },
          },
        },
        invert: {
          css: {
            color: theme("colors.neutral.100"),
            h1: { color: theme("colors.neutral.0") },
            h2: { color: theme("colors.neutral.0") },
            h3: { color: theme("colors.neutral.0") },
            a:  { color: theme("colors.brand.300") },
            strong: { color: theme("colors.neutral.0") },
          },
        },
      }),
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    // Optional (recommended):
    // require("@tailwindcss/typography"),
    // require("@tailwindcss/forms"),
  ],
} satisfies Config
