// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { env } from '@/config/env';
import type { Database } from './types';

const storage = typeof window === 'undefined' ? undefined : window.localStorage;
const isTest = Boolean(import.meta.env?.VITEST);

if (!env.supabaseUrl || !env.supabaseAnonKey) {
  if (!isTest) {
    throw new Error('Supabase credentials are missing. Check your environment configuration.');
  }
}

export const supabase = createClient<Database>(env.supabaseUrl || 'http://localhost', env.supabaseAnonKey || 'anon-key', {
  auth: {
    storage,
    persistSession: Boolean(storage),
    autoRefreshToken: Boolean(storage),
  },
});
