name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        # Remove lock file and do fresh install to avoid sync issues
        rm -f package-lock.json
        npm install
      
    - name: Create environment file
      run: |
        echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env.local
        echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env.local
        echo "VITE_SUPABASE_FUNCTIONS_URL=${{ secrets.VITE_SUPABASE_FUNCTIONS_URL }}" >> .env.local
        echo "VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}" >> .env.local
        echo "VITE_MAPBOX_ACCESS_TOKEN=${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}" >> .env.local
        
    - name: Build web assets
      run: npm run build
      
    - name: Setup Capacitor
      run: |
        npm install -g @capacitor/cli
        npx cap sync ios
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Create iOS project if not exists
      run: |
        if [ ! -d "ios" ]; then
          npx cap add ios
        fi
        npx cap sync ios
        
    - name: Update iOS project settings
      run: |
        # Update bundle identifier and app name
        sed -i '' 's/app.lovable.f63ed2d9b24c482abacd65518a3b8e6f/com.yardpass.app/g' ios/App/App.xcodeproj/project.pbxproj
        sed -i '' 's/yardpass-upgrade/YardPass/g' ios/App/App.xcodeproj/project.pbxproj
        
    - name: Build iOS app (Debug)
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
                   -scheme App \
                   -configuration Debug \
                   -destination 'generic/platform=iOS' \
                   -archivePath App.xcarchive \
                   archive
                   
    - name: Export IPA
      run: |
        cd ios/App
        # Create export options plist
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string>\${{ secrets.APPLE_TEAM_ID }}</string>
        </dict>
        </plist>
        EOF
        
        xcodebuild -exportArchive \
                   -archivePath App.xcarchive \
                   -exportPath . \
                   -exportOptionsPlist ExportOptions.plist
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: YardPass-iOS-${{ github.sha }}
        path: ios/App/*.ipa
        retention-days: 30
        
    # TestFlight upload disabled - requires Apple Developer account
    # - name: Upload to TestFlight (requires Apple Developer account)
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     xcrun altool --upload-app \
    #                  --type ios \
    #                  --file ios/App/*.ipa \
    #                  --apiKey ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }} \
    #                  --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
